### ISSUE TITLE
Include fields with no explicit resolver function in stats.

### ISSUE THREAD

**Issue by n1mmy** [apollostack/optics-agent-js#20]
We'd do this by providing and wrapping a no-op resolver in `instrumentSchema`

Not sure this is a good idea - it may impact server performance.

We can already get the number of times the field appears in _queries_ without this. This is only to get how many times such fields show up in _results_

**Comment by zhenyasav** [comment]
- let's show in reports that a resolver function is missing (post GA)

**Comment by n1mmy** [comment]
Yes, lets try this.
