### ISSUE TITLE
Protect against disabled agent

### ISSUE THREAD

**Issue by grydstedt** [apollostack/optics-agent-js#35]
Was debugging something in production and had to disable optics agent to identify cause of issue. The agent seems to not deal well with being half integrated:

If the agent is just instantiated without being hooked up in middleware I get this error:
[node_modules/optics-agent/dist/Report.js:273] EEE [TypeError: Cannot read property 'getTypeMap' of undefined]

If the agent is instantiated and `instrumentSchema` is called, but not put into middleware, all requests will break with:
[lib/api/controllers/graphql/graphql.jsx:28] Cannot read property 'startHrTime' of undefined

**Comment by n1mmy** [comment]
Good point! Thanks, @grydstedt!

**Comment by n1mmy** [comment]
Related #17. The `EEE` is an example of the poor error handling to be reworked.

We should probably log once (at startup or first query depending on the exact way the agent was disabled) saying what's wrong and why the agent is disabled. This can also help towards making the setup dev ux smoother (#22)

**Comment by grydstedt** [comment]
Sounds good!
